# Generated by Django 3.2.9 on 2021-11-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.URLField(unique=True),
        ),
    ]
