# Generated by Django 3.2.9 on 2021-11-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_rename_category_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='books.Category'),
        ),
    ]
