# Generated by Django 3.2.9 on 2021-11-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='fav_books', to='books.Book'),
        ),
    ]
